//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advertise.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _122 {
            get {
                object obj = ResourceManager.GetObject("_122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34 {
            get {
                object obj = ResourceManager.GetObject("_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53 {
            get {
                object obj = ResourceManager.GetObject("_53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_1_ {
            get {
                object obj = ResourceManager.GetObject("add_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_2_ {
            get {
                object obj = ResourceManager.GetObject("add_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;فرش ماهان\&quot;,\&quot;token\&quot;:\&quot;AY4rDkDp\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;اهواز\&quot;,\&quot;district\&quot;:\&quot;بهارستان\&quot;,\&quot;category\&quot;:\&quot;فرش و گلیم\&quot;,\&quot;category_hierarchy\&quot;:[\&quot;ROOT\&quot;,\&quot;for-the-home\&quot;,\&quot;furniture-and-home-decore\&quot;,\&quot;carpets\&quot;],\&quot;topDescription\&quot;:\&quot;۱,۶۰۰,۰۰۰ تومان\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در بهارستان\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[{\&quot;src\&quot;:\&quot;https:\u002F\u002Fs100.divarcdn.com\u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AhvazRegions {
            get {
                return ResourceManager.GetString("AhvazRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap article_1_ {
            get {
                object obj = ResourceManager.GetObject("article_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap D1 {
            get {
                object obj = ResourceManager.GetObject("D1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_1_ {
            get {
                object obj = ResourceManager.GetObject("delete_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_1_ {
            get {
                object obj = ResourceManager.GetObject("edit_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;لاجیتک\&quot;,\&quot;token\&quot;:\&quot;AY4nzCWY\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;اصفهان\&quot;,\&quot;district\&quot;:\&quot;احمدآباد\&quot;,\&quot;category\&quot;:\&quot;قطعات و لوازم جانبی\&quot;,\&quot;category_hierarchy\&quot;:[\&quot;ROOT\&quot;,\&quot;electronic-devices\&quot;,\&quot;computers\&quot;,\&quot;parts-and-accessories\&quot;],\&quot;topDescription\&quot;:\&quot;۳۰۰,۰۰۰ تومان\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در احمدآباد\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[{\&quot;src\&quot;:\&quot;https:\u002F\u002Fs100.divarc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsfahanRegions {
            get {
                return ResourceManager.GetString("IsfahanRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;آپارتمان  خوش نقشه\&quot;,\&quot;token\&quot;:\&quot;AY0_g45w\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;کرج\&quot;,\&quot;district\&quot;:\&quot;منظریه\&quot;,\&quot;category\&quot;:\&quot;آپارتمان\&quot;,\&quot;category_hierarchy\&quot;:[\&quot;ROOT\&quot;,\&quot;real-estate\&quot;,\&quot;residential-sell\&quot;,\&quot;apartment-sell\&quot;],\&quot;topDescription\&quot;:\&quot;۵۰۰,۰۰۰,۰۰۰ تومان\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در منظریه\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[{\&quot;src\&quot;:\&quot;https:\u002F\u002Fs100.divarcdn.com\u0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KarajRegions {
            get {
                return ResourceManager.GetString("KarajRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;ساعت مچی زنانه\&quot;,\&quot;token\&quot;:\&quot;AYfb_Wvi\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;مشهد\&quot;,\&quot;district\&quot;:\&quot;قاسم‌آباد (شهرک غرب)\&quot;,\&quot;category\&quot;:\&quot;ساعت\&quot;,\&quot;topDescription\&quot;:\&quot;۲۵,۰۰۰ تومان\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در قاسم‌آباد (شهرک غرب)\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[],\&quot;url\&quot;:\&quot;\u002Fv\u002F%D8%B3%D8%A7%D8%B9%D8%AA-%D9%85%DA%86%DB%8C-%D8%B2%D9%86%D8%A7%D9%86%D9%87_%D8%B3%D8%A7%D8%B9%D8%A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MashhadRegions {
            get {
                return ResourceManager.GetString("MashhadRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;کفش پسرونه سایز 29\&quot;,\&quot;token\&quot;:\&quot;AY4rjzlq\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;قم\&quot;,\&quot;district\&quot;:\&quot;هفت تیر\&quot;,\&quot;category\&quot;:\&quot;کفش و لباس بچه\&quot;,\&quot;category_hierarchy\&quot;:[\&quot;ROOT\&quot;,\&quot;personal\&quot;,\&quot;childrens-clothing-and-shoe\&quot;],\&quot;topDescription\&quot;:\&quot;۱۰۰,۰۰۰ تومان\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در هفت تیر\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[{\&quot;src\&quot;:\&quot;https:\u002F\u002Fs100.divarcdn.com\u002Fstati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QomRegions {
            get {
                return ResourceManager.GetString("QomRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_round_symbol {
            get {
                object obj = ResourceManager.GetObject("refresh_round_symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;گیرنده دیجیتال\&quot;,\&quot;token\&quot;:\&quot;AY4zjGph\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;شیراز\&quot;,\&quot;district\&quot;:\&quot;اطلسی\&quot;,\&quot;category\&quot;:\&quot;همه‌ی آگهی‌های صوتی و تصویری\&quot;,\&quot;category_hierarchy\&quot;:[\&quot;ROOT\&quot;,\&quot;electronic-devices\&quot;,\&quot;audio-video\&quot;],\&quot;topDescription\&quot;:\&quot;توافقی\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در اطلسی\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:false,\&quot;images\&quot;:[],\&quot;url\&quot;:\&quot;\u002Fv\u002F%DA%AF%DB%8C%D8%B1%D9%86%D8%AF%D9%8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShirazRegions {
            get {
                return ResourceManager.GetString("ShirazRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sms_status {
            get {
                object obj = ResourceManager.GetObject("sms_status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_checkbox {
            get {
                object obj = ResourceManager.GetObject("tab_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_checkbox_ {
            get {
                object obj = ResourceManager.GetObject("tab_checkbox_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_checkbox__ {
            get {
                object obj = ResourceManager.GetObject("tab_checkbox__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_close_ {
            get {
                object obj = ResourceManager.GetObject("tab_close_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;آموزش تعمیرات موبایل به همراه استخدام\&quot;,\&quot;token\&quot;:\&quot;wXTPYtjh\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;تهران\&quot;,\&quot;district\&quot;:\&quot;میدان انقلاب\&quot;,\&quot;category\&quot;:\&quot;رایانه و فناوری اطلاعات\&quot;,\&quot;category_hierarchy\&quot;:[\&quot;ROOT\&quot;,\&quot;jobs\&quot;,\&quot;computer-and-it\&quot;],\&quot;topDescription\&quot;:\&quot;\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در میدان انقلاب\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[{\&quot;src\&quot;:\&quot;https:\u002F\u002Fs100.divarcdn.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TehranRegions {
            get {
                return ResourceManager.GetString("TehranRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{\&quot;browse\&quot;:{\&quot;items\&quot;:[{\&quot;type\&quot;:\&quot;POST\&quot;,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;ساعت مچی زنانه\&quot;,\&quot;token\&quot;:\&quot;AYfb_Wvi\&quot;,\&quot;image_top_left_tag\&quot;:null,\&quot;index\&quot;:0,\&quot;postapi-version\&quot;:1,\&quot;city\&quot;:\&quot;مشهد\&quot;,\&quot;district\&quot;:\&quot;قاسم‌آباد (شهرک غرب)\&quot;,\&quot;category\&quot;:\&quot;ساعت\&quot;,\&quot;topDescription\&quot;:\&quot;۲۵,۰۰۰ تومان\&quot;,\&quot;bottomDescription\&quot;:\&quot;لحظاتی پیش در قاسم‌آباد (شهرک غرب)\&quot;,\&quot;redText\&quot;:\&quot;\&quot;,\&quot;hasChat\&quot;:true,\&quot;images\&quot;:[],\&quot;url\&quot;:\&quot;\u002Fv\u002F%D8%B3%D8%A7%D8%B9%D8%AA-%D9%85%DA%86%DB%8C-%D8%B2%D9%86%D8%A7%D9%86%D9%87_%D8%B3%D8%A7%D8%B9%D8%A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolbarButton_print {
            get {
                object obj = ResourceManager.GetObject("toolbarButton_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
