using System;
using System.Collections.Generic;
using EntityCache.Bussines;
using Services;
using Services.DefaultCoding;

namespace EntityCache.Assistence.Defualts
{
    public class DefaultMoein
    {
        private static List<MoeinBussines> list = new List<MoeinBussines>();
        private static MoeinBussines SetDef(string name, string code, Guid guid, Guid kolGuid)
        {
            try
            {
                var state = new MoeinBussines()
                {
                    Name = name,
                    Account = 0,
                    Guid = guid,
                    Code = code,
                    KolGuid = kolGuid
                };
                return state;
            }
            catch (Exception ex)
            {
                WebErrorLog.ErrorInstence.StartErrorLog(ex);
                return null;
            }
        }
        public static List<MoeinBussines> SetDef()
        {
            try
            {
                list.Add(SetDef("موجودی نزد بانک ها", "10101", ParentDefaults.MoeinCoding.CLSMoein10101, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("موجودی نزد صندوق ها", "10102", ParentDefaults.MoeinCoding.CLSMoein10102, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("موجودی نزد تنخواه گردان", "10103", ParentDefaults.MoeinCoding.CLSMoein10103, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("اسناد و اوراق بهادار نزد صندوق", "10104", ParentDefaults.MoeinCoding.CLSMoein10104, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("وجوه در راه", "10105", ParentDefaults.MoeinCoding.CLSMoein10105, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("موجودی واریزی نامه های ارزی", "10106", ParentDefaults.MoeinCoding.CLSMoein10106, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("مسکوکات", "10107", ParentDefaults.MoeinCoding.CLSMoein10107, ParentDefaults.KolCoding.ClsKol101));
                list.Add(SetDef("سپرده سرمایه گذاری", "10201", ParentDefaults.MoeinCoding.CLSMoein10201, ParentDefaults.KolCoding.ClsKol102));
                list.Add(SetDef("سرمایه گذاری در سهام", "10202", ParentDefaults.MoeinCoding.CLSMoein10202, ParentDefaults.KolCoding.ClsKol102));
                list.Add(SetDef("سرمایه گذاری در اوراق مشارکت", "10203", ParentDefaults.MoeinCoding.CLSMoein10203, ParentDefaults.KolCoding.ClsKol102));
                list.Add(SetDef("اسناد دریافتنی تجاری درجریان وصول", "10301", ParentDefaults.MoeinCoding.CLSMoein10301, ParentDefaults.KolCoding.ClsKol103));
                list.Add(SetDef("اسناد دریافتنی تجاری نزد صندوق", "10302", ParentDefaults.MoeinCoding.CLSMoein10302, ParentDefaults.KolCoding.ClsKol103));
                list.Add(SetDef("اسناد دریافتنی تجاری واخواستی", "10303", ParentDefaults.MoeinCoding.CLSMoein10303, ParentDefaults.KolCoding.ClsKol103));
                list.Add(SetDef("حساب های دریافتنی تجاری", "10304", ParentDefaults.MoeinCoding.CLSMoein10304, ParentDefaults.KolCoding.ClsKol103));
                list.Add(SetDef("اسناد دریافتنی غیرتجاری در جریان وصول", "10401", ParentDefaults.MoeinCoding.CLSMoein10401, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("اسناد دریافتنی غیرتجاری نزد صندوق", "10402", ParentDefaults.MoeinCoding.CLSMoein10402, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("اسناد دریافتنی غیر تجاری واخواستی", "10403", ParentDefaults.MoeinCoding.CLSMoein10403, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("حساب های دریافتنی غیر تجاری", "10404", ParentDefaults.MoeinCoding.CLSMoein10404, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("مساعده کارکنان", "10405", ParentDefaults.MoeinCoding.CLSMoein10405, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("وام ضروری کارکنان", "10406", ParentDefaults.MoeinCoding.CLSMoein10406, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("حق العمل کاران", "10407", ParentDefaults.MoeinCoding.CLSMoein10407, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("ترخیص کاران گمرکی", "10408", ParentDefaults.MoeinCoding.CLSMoein10408, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("سپرده های موقت", "10409", ParentDefaults.MoeinCoding.CLSMoein10409, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("سود سهام دریافتنی", "10410", ParentDefaults.MoeinCoding.CLSMoein10410, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("طلب از شرکت های گروه", "10411", ParentDefaults.MoeinCoding.CLSMoein10411, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("طلب از سایر اشخاص وابسته", "10412", ParentDefaults.MoeinCoding.CLSMoein10412, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("خسارت قابل دریافت از بیمه", "10413", ParentDefaults.MoeinCoding.CLSMoein10413, ParentDefaults.KolCoding.ClsKol104));
                list.Add(SetDef("موجودی مواد اولیه", "10501", ParentDefaults.MoeinCoding.CLSMoein10501, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("موجودی قطعات و لوازم یدکی", "10502", ParentDefaults.MoeinCoding.CLSMoein10502, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("مواد کمکی و بسته بندی", "10503", ParentDefaults.MoeinCoding.CLSMoein10503, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("کالای درجریان ساخت", "10504", ParentDefaults.MoeinCoding.CLSMoein10504, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("کالای ساخته شده", "10505", ParentDefaults.MoeinCoding.CLSMoein10505, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("موجودی در راه", "10506", ParentDefaults.MoeinCoding.CLSMoein10506, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("کالای امانی ما نزد دیگران", "10507", ParentDefaults.MoeinCoding.CLSMoein10507, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("موجودی اقلام راکد و ناباب", "10508", ParentDefaults.MoeinCoding.CLSMoein10508, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("موجودی ضایعات مواد اولیه", "10509", ParentDefaults.MoeinCoding.CLSMoein10509, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("موجودی ضایعات قطعاتو لوازم یدکی", "10510", ParentDefaults.MoeinCoding.CLSMoein10510, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("انحراف نرخ مواد اولیه هنگام خرید", "10511", ParentDefaults.MoeinCoding.CLSMoein10511, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("انحرافات کالای درجریان ساخت", "10512", ParentDefaults.MoeinCoding.CLSMoein10512, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("سایر موجودی ها", "10513", ParentDefaults.MoeinCoding.CLSMoein10513, ParentDefaults.KolCoding.ClsKol105));
                list.Add(SetDef("پیش پرداخت خرید", "10601", ParentDefaults.MoeinCoding.CLSMoein10601, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("پیش پرداخت خدمات", "10602", ParentDefaults.MoeinCoding.CLSMoein10602, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("پیش پرداخت بیمه", "10603", ParentDefaults.MoeinCoding.CLSMoein10603, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("پیش پرداخت مالیات", "10604", ParentDefaults.MoeinCoding.CLSMoein10604, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("پیش پرداخت به پیمانکاران", "10605", ParentDefaults.MoeinCoding.CLSMoein10605, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("سایر پیش پرداخت ها", "10606", ParentDefaults.MoeinCoding.CLSMoein10606, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("سفارشات مواد اولیه", "10607", ParentDefaults.MoeinCoding.CLSMoein10607, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("سفارشات کالا", "10608", ParentDefaults.MoeinCoding.CLSMoein10608, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("سفارشات قطعات و لوازم یدکی", "10609", ParentDefaults.MoeinCoding.CLSMoein10609, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("سفارشات ماشین آلات", "10610", ParentDefaults.MoeinCoding.CLSMoein10610, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("موجودی تمبر و سفته", "10611", ParentDefaults.MoeinCoding.CLSMoein10611, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("هزینه های قبل از گشایش اعتبار سفارش", "10612", ParentDefaults.MoeinCoding.CLSMoein10612, ParentDefaults.KolCoding.ClsKol106));
                list.Add(SetDef("سپرده بیمه", "10701", ParentDefaults.MoeinCoding.CLSMoein10701, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("سپرده حسن انجام کار", "10702", ParentDefaults.MoeinCoding.CLSMoein10702, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("سپرده حسن اجرای تعهدات", "10703", ParentDefaults.MoeinCoding.CLSMoein10703, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("سپرده شرکت در مناقصات", "10704", ParentDefaults.MoeinCoding.CLSMoein10704, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("سپرده شرکت در مزایده", "10705", ParentDefaults.MoeinCoding.CLSMoein10705, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("سپرده نزد بانک ها", "10706", ParentDefaults.MoeinCoding.CLSMoein10706, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("سپرده های گمرکی", "10707", ParentDefaults.MoeinCoding.CLSMoein10707, ParentDefaults.KolCoding.ClsKol107));
                list.Add(SetDef("زمین", "20101", ParentDefaults.MoeinCoding.CLSMoein20101, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("ساختمان", "20102", ParentDefaults.MoeinCoding.CLSMoein20102, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("تاسیسات", "20103", ParentDefaults.MoeinCoding.CLSMoein20103, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("ماشین آلات و تجهیزات", "20104", ParentDefaults.MoeinCoding.CLSMoein20104, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("ابزارآلات", "20105", ParentDefaults.MoeinCoding.CLSMoein20105, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("وسائط نقلیه", "20106", ParentDefaults.MoeinCoding.CLSMoein20106, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("اثاثیه و منصوبات", "20107", ParentDefaults.MoeinCoding.CLSMoein20107, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("قالب ها", "20108", ParentDefaults.MoeinCoding.CLSMoein20108, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("لوازم آزمایشگاهی", "20109", ParentDefaults.MoeinCoding.CLSMoein20109, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("دارایی های سرمایه ای موجود در انبار", "20110", ParentDefaults.MoeinCoding.CLSMoein20110, ParentDefaults.KolCoding.ClsKol201));
                list.Add(SetDef("ساختمان", "20202", ParentDefaults.MoeinCoding.CLSMoein20202, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("تاسیسات", "20203", ParentDefaults.MoeinCoding.CLSMoein20203, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("ماشین آلات و تجهیزات", "20204", ParentDefaults.MoeinCoding.CLSMoein20204, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("ابزارآلات", "20205", ParentDefaults.MoeinCoding.CLSMoein20205, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("وسائط نقلیه", "20206", ParentDefaults.MoeinCoding.CLSMoein20206, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("اثاثیه و منصوبات", "20207", ParentDefaults.MoeinCoding.CLSMoein20207, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("قالب ها", "20208", ParentDefaults.MoeinCoding.CLSMoein20208, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("لوازم آزمایشگاهی", "20209", ParentDefaults.MoeinCoding.CLSMoein20209, ParentDefaults.KolCoding.ClsKol202));
                list.Add(SetDef("ساختمان در جریان تکمیل", "20301", ParentDefaults.MoeinCoding.CLSMoein20301, ParentDefaults.KolCoding.ClsKol203));
                list.Add(SetDef("تاسیسات در جریان تکمیل", "20302", ParentDefaults.MoeinCoding.CLSMoein20302, ParentDefaults.KolCoding.ClsKol203));
                list.Add(SetDef("ماشین آلات در جریان تکمیل", "20303", ParentDefaults.MoeinCoding.CLSMoein20303, ParentDefaults.KolCoding.ClsKol203));
                list.Add(SetDef("ابزارآلات در جریان تکمیل", "20304", ParentDefaults.MoeinCoding.CLSMoein20304, ParentDefaults.KolCoding.ClsKol203));
                list.Add(SetDef("قالب های در جریان تکمیل", "20305", ParentDefaults.MoeinCoding.CLSMoein20305, ParentDefaults.KolCoding.ClsKol203));
                list.Add(SetDef("حق الامتیاز ها", "20401", ParentDefaults.MoeinCoding.CLSMoein20401, ParentDefaults.KolCoding.ClsKol204));
                list.Add(SetDef("حق استفاده از خدمات عمومی", "20402", ParentDefaults.MoeinCoding.CLSMoein20402, ParentDefaults.KolCoding.ClsKol204));
                list.Add(SetDef("سرقفلی محل کسب", "20403", ParentDefaults.MoeinCoding.CLSMoein20403, ParentDefaults.KolCoding.ClsKol204));
                list.Add(SetDef("نرم افزارها", "20404", ParentDefaults.MoeinCoding.CLSMoein20404, ParentDefaults.KolCoding.ClsKol204));
                list.Add(SetDef("سیستم ها و روش ها", "20405", ParentDefaults.MoeinCoding.CLSMoein20405, ParentDefaults.KolCoding.ClsKol204));
                list.Add(SetDef("سایر دارایی های نامشهود", "20406", ParentDefaults.MoeinCoding.CLSMoein20406, ParentDefaults.KolCoding.ClsKol204));
                list.Add(SetDef("سرمایه گذاری در سهام شرکت ها", "20501", ParentDefaults.MoeinCoding.CLSMoein20501, ParentDefaults.KolCoding.ClsKol205));
                list.Add(SetDef("سرمایه گذاری در اوراق مشارکت", "20502", ParentDefaults.MoeinCoding.CLSMoein20502, ParentDefaults.KolCoding.ClsKol205));
                list.Add(SetDef("سپرده های بانکی", "20503", ParentDefaults.MoeinCoding.CLSMoein20503, ParentDefaults.KolCoding.ClsKol205));
                list.Add(SetDef("وام های اعطایی", "20504", ParentDefaults.MoeinCoding.CLSMoein20504, ParentDefaults.KolCoding.ClsKol205));
                list.Add(SetDef("مخارج انتقالی به دوره های آتی", "20601", ParentDefaults.MoeinCoding.CLSMoein20601, ParentDefaults.KolCoding.ClsKol299));
                list.Add(SetDef("وجه نقد مسدود شده نزد بانک", "20602", ParentDefaults.MoeinCoding.CLSMoein20602, ParentDefaults.KolCoding.ClsKol299));
                list.Add(SetDef("وجه نقد کنار گذاشته شده برای هدف مشخص", "20603", ParentDefaults.MoeinCoding.CLSMoein20603, ParentDefaults.KolCoding.ClsKol299));
                list.Add(SetDef("اسناد دریافتنی بلندمدت", "20604", ParentDefaults.MoeinCoding.CLSMoein20604, ParentDefaults.KolCoding.ClsKol299));
                list.Add(SetDef("حصه بلندمدت وام کارکنان", "20605", ParentDefaults.MoeinCoding.CLSMoein20605, ParentDefaults.KolCoding.ClsKol299));
                list.Add(SetDef("اسناد پرداختنی تجاری", "30101", ParentDefaults.MoeinCoding.CLSMoein30101, ParentDefaults.KolCoding.ClsKol301));
                list.Add(SetDef("معلق خرید", "30102", ParentDefaults.MoeinCoding.CLSMoein30102, ParentDefaults.KolCoding.ClsKol301));
                list.Add(SetDef("حساب های پرداختنی تجاری", "30103", ParentDefaults.MoeinCoding.CLSMoein30103, ParentDefaults.KolCoding.ClsKol301));
                list.Add(SetDef("اسناد پرداختنی غیرتجاری", "30201", ParentDefaults.MoeinCoding.CLSMoein30201, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("حساب های پرداختنی غیر تجاری", "30202", ParentDefaults.MoeinCoding.CLSMoein30202, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("مالیات های تکمیلی پرداختنی", "30203", ParentDefaults.MoeinCoding.CLSMoein30203, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("مالیات بر درآمد شرکت پرداختنی", "30204", ParentDefaults.MoeinCoding.CLSMoein30204, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("حق بیمه پرداختنی", "30205", ParentDefaults.MoeinCoding.CLSMoein30205, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("حقوق و دستمزد پرداختنی", "30206", ParentDefaults.MoeinCoding.CLSMoein30206, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("عوارض شهرداری", "30207", ParentDefaults.MoeinCoding.CLSMoein30207, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("دو در هزار فروش صنایع", "30208", ParentDefaults.MoeinCoding.CLSMoein30208, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("یک در هزار تربیت بدنی", "30209", ParentDefaults.MoeinCoding.CLSMoein30209, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("عوارض آموزش و پرورش", "30210", ParentDefaults.MoeinCoding.CLSMoein30210, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("ذخیره هزینه های معوق پرداخت نشده", "30211", ParentDefaults.MoeinCoding.CLSMoein30211, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("حساب های پرداختنی", "30212", ParentDefaults.MoeinCoding.CLSMoein30212, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("جاری شرکا", "30213", ParentDefaults.MoeinCoding.CLSMoein30213, ParentDefaults.KolCoding.ClsKol302));
                list.Add(SetDef("پیش دریافت فروش", "30301", ParentDefaults.MoeinCoding.CLSMoein30301, ParentDefaults.KolCoding.ClsKol303));
                list.Add(SetDef("پیش دریافت ارائه خدمات", "30302", ParentDefaults.MoeinCoding.CLSMoein30302, ParentDefaults.KolCoding.ClsKol303));
                list.Add(SetDef("سایر پیش دریافت ها", "30303", ParentDefaults.MoeinCoding.CLSMoein30303, ParentDefaults.KolCoding.ClsKol303));
                list.Add(SetDef("ذخیره مالیات بر درآمد شرکت ها", "30401", ParentDefaults.MoeinCoding.CLSMoein30401, ParentDefaults.KolCoding.ClsKol304));
                list.Add(SetDef("سود سهام پرداختنی", "30501", ParentDefaults.MoeinCoding.CLSMoein30501, ParentDefaults.KolCoding.ClsKol305));
                list.Add(SetDef("سپرده حسن انجام کار", "30601", ParentDefaults.MoeinCoding.CLSMoein30601, ParentDefaults.KolCoding.ClsKol306));
                list.Add(SetDef("سپرده حسن اجرای تعهدات", "30602", ParentDefaults.MoeinCoding.CLSMoein30602, ParentDefaults.KolCoding.ClsKol306));
                list.Add(SetDef("سپرده دریافتی مزایده", "30603", ParentDefaults.MoeinCoding.CLSMoein30603, ParentDefaults.KolCoding.ClsKol306));
                list.Add(SetDef("سپرده دریافتی مناقصه", "30604", ParentDefaults.MoeinCoding.CLSMoein30604, ParentDefaults.KolCoding.ClsKol306));
                list.Add(SetDef("سایر سپرده های دریافتی", "30605", ParentDefaults.MoeinCoding.CLSMoein30605, ParentDefaults.KolCoding.ClsKol306));
                list.Add(SetDef("فروش اقساطی", "30701", ParentDefaults.MoeinCoding.CLSMoein30701, ParentDefaults.KolCoding.ClsKol307));
                list.Add(SetDef("سلف", "30702", ParentDefaults.MoeinCoding.CLSMoein30702, ParentDefaults.KolCoding.ClsKol307));
                list.Add(SetDef("مشارکت مدنی", "30703", ParentDefaults.MoeinCoding.CLSMoein30703, ParentDefaults.KolCoding.ClsKol307));
                list.Add(SetDef("مضاربه", "30704", ParentDefaults.MoeinCoding.CLSMoein30704, ParentDefaults.KolCoding.ClsKol307));
                list.Add(SetDef("ذخیره مطالبات مشکوک الوصول", "30801", ParentDefaults.MoeinCoding.CLSMoein30801, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("ذخیره کاهش ارزش موجودی مواد", "30802", ParentDefaults.MoeinCoding.CLSMoein30802, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("ذخیره کاهش ارزش قطعات و ملزومات مصرفی", "30803", ParentDefaults.MoeinCoding.CLSMoein30803, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("ذخیره کاهش ارزش موجودی کالا", "30804", ParentDefaults.MoeinCoding.CLSMoein30804, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("ذخیره بن کارگری", "30805", ParentDefaults.MoeinCoding.CLSMoein30805, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("ذخیره تضمین محصولات", "30806", ParentDefaults.MoeinCoding.CLSMoein30806, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("ذخیره مرخصی استفاده نشده", "30807", ParentDefaults.MoeinCoding.CLSMoein30807, ParentDefaults.KolCoding.ClsKol308));
                list.Add(SetDef("اسناد پرداختنی بلند مدت تجاری", "40101", ParentDefaults.MoeinCoding.CLSMoein40101, ParentDefaults.KolCoding.ClsKol401));
                list.Add(SetDef("حساب های پرداختنی بلندمدت تجاری", "40102", ParentDefaults.MoeinCoding.CLSMoein40102, ParentDefaults.KolCoding.ClsKol401));
                list.Add(SetDef("اسناد پرداختنی بلندمدت غیر تجاری", "40201", ParentDefaults.MoeinCoding.CLSMoein40101, ParentDefaults.KolCoding.ClsKol402));
                list.Add(SetDef("حساب های پرداختنی بلند مدت غیر تجاری", "40202", ParentDefaults.MoeinCoding.CLSMoein40102, ParentDefaults.KolCoding.ClsKol402));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));
                list.Add(SetDef("", "",,));

                return list;
            }
            catch (Exception ex)
            {
                WebErrorLog.ErrorInstence.StartErrorLog(ex);
                return null;
            }
        }
    }
}
