// <auto-generated />
namespace Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _69 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_69));
        
        string IMigrationMetadata.Id
        {
            get { return "202102251159573__69"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
