// <auto-generated />
namespace Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _75 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_75));
        
        string IMigrationMetadata.Id
        {
            get { return "202103041716437__75"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
